[package]
name = "zed_haskell"
version = "0.1.6"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/haskell.rs"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.149"
zed_extension_api = {path = "../Projects/zed/crates/extension_api"}
